name: podcast_project
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  # Firebase core
  firebase_core: ^3.8.0

  # Authentification avec Firebase
  firebase_auth: ^5.3.3

  # Firestore pour les posts et données utilisateurs
  cloud_firestore: ^5.5.0

  # Riverpod (gestion d'état)
  flutter_riverpod: ^2.6.1

  # Gestion des images
  cached_network_image: ^3.4.1 # Pour charger et mettre en cache les images

  # Gestion des vidéos
  video_player: ^2.5.3 # Pour lire les vidéos dans les posts
  chewie: ^1.4.2 # Contrôles personnalisés pour le lecteur vidéo

  # Formulaires et validations
  flutter_form_builder: ^9.5.0
  form_builder_validators: ^11.0.0
  go_router: ^14.6.0

  # UI (animations et design)
  flutter_svg: ^2.0.7 # Pour charger des fichiers SVG
  animations: ^2.0.6 # Pour des animations pré-construites

  # Stockage local
  shared_preferences: ^2.2.2 # Pour stocker les sessions utilisateur

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  equatable: ^2.0.7
  just_audio: ^0.9.42
  audioplayers: ^6.1.0
  flutter_screenutil: ^5.9.3
  audio_service: ^0.18.15
  get: ^4.6.6
  on_audio_query: ^2.9.0
  transparent_image: ^2.0.1
  permission_handler: ^11.3.1
  audio_video_progress_bar: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.13


flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images/google.png
    - assets/images/facebook.png
    - assets/images/background.jpeg
    - assets/musics/
    - assets/evenement.gif

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
